site_name: GrassBot
site_url: https://sitename.example

theme:
  name: material
  palette:
    primary: green
    accent: light green
  font:
    text: Roboto
    code: Roboto Mono
nav:
  - Home: index.md
  - Detalhamento do Problema: detalhamento.md
  - Requisitos: requisitos.md
  - Arquitetura: arquitetura.md
