site_name: GrassBot
site_url: https://sitename.example

theme:
  name: material
  palette:
    scheme: slate
    primary: green
nav:
  - Home: index.md
  - Detalhamento do Problema: detalhamento.md
  - Requisitos: requisitos.md
  - Arquitetura: arquitetura.md
